### ISSUE TITLE
hasty.attribute.Attribute.edit() - Project ID is None + Optional parameters required

### ISSUE THREAD

**Issue by DevGlitch** [hasty-ai/hasty-python#24]
When trying to use the function to edit an attribute I ran into two issues.

**Issues:**
1. The two optional arguments `description` and `norder` are actually required
`TypeError: edit() missing 2 required positional arguments: 'description' and 'norder'`

2. Running the function will give you an error 500 due to the project id being `None`
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.hasty.ai/v1/projects/None/attributes/9883afc3-2a5d-44b5-abd0-c83e7f37bc40`

**Solutions:**
1. Use `Optional` from typing to make the two parameters optional:
`description: Optional[str] = None, norder: Optional[float] = None`
You could also do in two other ways: `description: str = None` or even `description: Union[str, None]`
It comes down to just a preference at the end, just think the Optional makes the code clear. :)
It would be good to apply this everywhere anything is optional as I noticed the issue in other functions in the API.
More than happy to submit a pull request if you'd like.

2. My quick fix was to add the project id as a required argument, but this is just a temporary workaround.
You would need to look into this as this issue might be present in other functions in the API.

**Comment by xeviknal** [comment]
hi @DevGlitch! Thank you for rising these issues. Let me find someone who can help you with and we'll prioritize for the next releases.
